sudo: false
services:
  - docker

language: cpp

# default values
os: linux
compiler: gcc

osx_image: xcode10.2

cache:
    directories:
      - $HOME/.cache

git:
    depth: 100500

jobs:
    include:
      - name: RelWithDebInfoWError build + test (Linux, gcc)
        env: TARGET=test
      - name: RelWithDebInfoWError build + test (Linux, clang)
        env: TARGET=test
        compiler: clang
      - name: RelWithDebInfoWError build + test (OS X 10.14 Mojave)
        env: TARGET=test
        os: osx
      - name: Debug build + test + coverage (Linux, gcc)
        env: TARGET=coverage
      - name: RelWithDebInfoWError build + test (OS X 10.13 xcode 10.1 Temporary check)
        env: TARGET=test
        os: osx
        osx_image: xcode10.1
      - name: RelWithDebInfoWError build + test (OS X 10.13 xcode 10 Temporary check)
        env: TARGET=test
        os: osx
        osx_image: xcode10
      - name: RelWithDebInfoWError build + test (OS X 10.13 xcode 9.4.1 High Sierra)
        env: TARGET=test
        os: osx
        osx_image: xcode9.4
        #if: branch = "2.1"
      - name: RelWithDebInfoWError build + test (OS X 10.13 xcode 9.3 Temporary check)
        env: TARGET=test
        os: osx
        osx_image: xcode9.3
      - name: RelWithDebInfoWError build + test (OS X 10.12 xcode 9.2 Temporary check)
        env: TARGET=test
        os: osx
        osx_image: xcode9.2
      - name: RelWithDebInfoWError build + test (OS X 10.12 xcode 9.1 Temporary check)
        env: TARGET=test
        os: osx
        osx_image: xcode9.1
      - name: RelWithDebInfoWError build + test (OS X 10.12 xcode 9.0 Temporary check)
        env: TARGET=test
        os: osx
        osx_image: xcode9
      - name: RelWithDebInfoWError build + test (OS X 10.12 xcode 8.3 Temporary check)
        env: TARGET=test
        os: osx
        osx_image: xcode8.3
      - name: RelWithDebInfoWError build + test (OS X 10.11 xcode 8 Temporary check)
        env: TARGET=test
        os: osx
        osx_image: xcode8
      - name: RelWithDebInfoWError build + test (OS X 10.11 xcode 7.3 Temporary check)
        env: TARGET=test
        os: osx
        osx_image: xcode7.3
      - name: LTO build + test (Linux, gcc)
        env: TARGET=test CMAKE_EXTRA_PARAMS=-DENABLE_LTO=ON
        if: branch = "2.1"
      - name: LTO build + test (Linux, clang)
        env: TARGET=test CMAKE_EXTRA_PARAMS=-DENABLE_LTO=ON
        if: branch = "2.1"
        compiler: clang
      - name: LTO build + test (OS X 10.14 Mojave)
        os: osx
        env: TARGET=test CMAKE_EXTRA_PARAMS=-DENABLE_LTO=ON
        #if: branch = "2.1"
      - name: Create and deploy tarball
        env: TARGET=source
        if: branch = "2.1"
      - name: CentOS 6 build + test + deploy RPM
        env: OS=el DIST=6
        if: branch = "2.1"
      - name: CentOS 7 build + test + deploy RPM
        env: OS=el DIST=7
        if: branch = "2.1"
      - name: Ubuntu Trusty (14.04) build + deploy DEB
        env: OS=ubuntu DIST=trusty
        if: branch = "2.1"
      - name: Ubuntu Xenial (16.04) build + deploy DEB
        env: OS=ubuntu DIST=xenial
        if: branch = "2.1"
      - name: Ubuntu Bionic (18.04) build + deploy DEB
        env: OS=ubuntu DIST=bionic
        if: branch = "2.1"
      - name: Ubuntu Cosmic (18.10) build + deploy DEB
        env: OS=ubuntu DIST=cosmic
        if: branch = "2.1"
      - name: Debian Wheezy (7) build + deploy DEB
        env: OS=debian DIST=wheezy
        if: branch = "2.1"
      - name: Debian Jessie (8) build + deploy DEB
        env: OS=debian DIST=jessie
        if: branch = "2.1"
      - name: Debian Stretch (9) build + deploy DEB
        env: OS=debian DIST=stretch
        if: branch = "2.1"

script:
  - make -f .travis.mk ${TARGET}

before_deploy:
  - ls -l build/

deploy:
  # Deploy packages to PackageCloud
  - provider: packagecloud
    username: "tarantool"
    repository: "2x"
    token: "${PACKAGECLOUD_TOKEN}"
    dist: "${OS}/${DIST}"
    package_glob: build/*.{rpm,deb,dsc}
    skip_cleanup: true
    on:
      repo: tarantool/tarantool
      branch: "2.1"
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  # Deploy source tarballs to S3
  - provider: script
    script: make -f .travis.mk source_deploy
    skip_cleanup: true
    on:
      repo: tarantool/tarantool
      branch: "2.1"
      condition: "x${TARGET} = xsource"

notifications:
  email:
    recipients:
      - build@tarantool.org
    on_success: change
    on_failure: always
